<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZucchiSecurity\Module'                        => __DIR__ . '/Module.php',
    'ZucchiSecurity\Controller\AdminController'      => __DIR__ . '/src/ZucchiSecurity/Controller/AdminController.php',
    'ZucchiSecurity\Controller\AuthController'      => __DIR__ . '/src/ZucchiSecurity/Controller/AuthController.php',
    'ZucchiSecurity\Controller\AcccessController'      => __DIR__ . '/src/ZucchiSecurity/Controller/AccessController.php',
);